# Generated by Django 4.2.15 on 2024-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPIapp', '0008_user_gender_alter_tasks_priority_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='mark',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='0', max_length=100),
        ),
    ]
