# Generated by Django 4.2.15 on 2024-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPIapp', '0012_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
